# 使用 Debian 11 (Bullseye) 作为基础镜像
FROM debian:11-slim

# 设置工作目录
WORKDIR /root/cfddns

# 安装所需的依赖，下载并解压 CloudflareSpeedTest 包，下载 CFDDNS.py 脚本，设置定时任务
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget \
    tar \
    cron \
    nano \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install requests tencentcloud-sdk-python \
    && wget https://raw.githubusercontent.com/fengyuanluo/box/main/Python%E9%A1%B9%E7%9B%AE%E4%B8%8D%E5%AE%8C%E5%85%A8%E7%89%88/CFDDNS/download_cfddns.sh -O /tmp/download_cfddns.sh \
    && sh /tmp/download_cfddns.sh \
    && rm /tmp/download_cfddns.sh \
    && wget https://raw.githubusercontent.com/fengyuanluo/box/main/Python%E9%A1%B9%E7%9B%AE%E4%B8%8D%E5%AE%8C%E5%85%A8%E7%89%88/CFDDNS/CFDDNS.py -O /root/cfddns/CFDDNS.py \
    && (crontab -l 2>/dev/null; echo "*/20 * * * * cd /root/cfddns && python3 CFDDNS.py") | crontab -

# 启动 cron 服务
CMD ["cron", "-f"]